# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0002_auto_20160111_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='volume_of_oocytes',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
